from .problem import BfItem as BfItem, ConstItem as ConstItem, Problem as Problem
from typing import Callable, Optional

def generic_solver(problem: Problem, cipher: bytes, hash_func: Callable[[bytearray], bytes]) -> Optional[bytes]: ...
def sha1_solver(problem: Problem, cipher: bytes) -> Optional[bytes]: ...
def sha224_solver(problem: Problem, cipher: bytes) -> Optional[bytes]: ...
def sha256_solver(problem: Problem, cipher: bytes) -> Optional[bytes]: ...
def sha384_solver(problem: Problem, cipher: bytes) -> Optional[bytes]: ...
def sha512_solver(problem: Problem, cipher: bytes) -> Optional[bytes]: ...
def md5_solver(problem: Problem, cipher: bytes) -> Optional[bytes]: ...
